---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag: "glob:test-*"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: drazul/dummy-app:test-1587416769
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app 
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: my-app

