---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-secrets
  labels:
    app: my-app-with-secrets
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag: "glob:test-*"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-with-secrets
  template:
    metadata:
      labels:
        app: my-app-with-secrets
    spec:
      containers:
        - name: my-app-with-secrets
          image: drazul/dummy-app:test-1587417995
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: my-secret
              readOnly: true
      volumes:
        - name: my-secret
          secret:
            secretName: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-with-secrets
  labels:
    app: my-app-with-secrets
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: my-app-with-secrets

